model_name: FFT_FFN
lookback: 30
dropout: 0.25
hidden_units: [30, 16, 8, 4] # must start with 30

# Data parameters
preprocess_func: "preprocess_fourier" # name of a function defined in pre_process.py
use_residual_weights: False # use residual composition matrix to compute turnover, short proportion, etc.
factor_models: # number of factors per residual time series to test, for each factor model
  { "IPCA": [5], "PCA": [5], "FamaFrench": [5] }
num_epochs: 100
lr: 0.001
batchsize: 125
# If mode=='estimate', this is the number of obs used to form a test set (chronologically after the training set)
retrain_freq: 125
rolling_retrain: True # Set to False for no rolling retraining (i.e. train once, test for all data past training set)
force_retrain: True # Force the model to be trained, even if existing weights for the model are saved on disk
length_training: 1000 # Size of rolling training window in trading days
early_stopping: False # Employ early stopping or not
objective: "sharpe"
# Market frictions parameters
market_frictions: False # enable or disable
trans_cost: 0 # cost in bps per txn side per equity, e.g. 0.0005
hold_cost: 0 # cost in bps for short positions per equity per day, e.g. 0.0001
parallelize: False

model_tag: "FFT"  # ToDo: What do we want to include? lookback, objective, trans_cost, hold_cost, num_epochs, lr ??
model_name_: "FFT_FFN"  # For saving in correct directory
device: "cuda"


# Residual paths
pca_0_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor0_rollingwindow_180.npz"
pca_1_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor1_rollingwindow_180.npz"
pca_3_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor3_rollingwindow_180.npz"
pca_5_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor5_rollingwindow_180.npz"
pca_8_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor8_rollingwindow_180.npz"
pca_10_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor10_rollingwindow_180.npz"
pca_15_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor15_rollingwindow_180.npz"

pca_0_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor0_rollingwindow_180.npz"
pca_1_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor1_rollingwindow_180.npz"
pca_3_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor3_rollingwindow_180.npz"
pca_5_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor5_rollingwindow_180.npz"
pca_8_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor8_rollingwindow_180.npz"
pca_10_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor10_rollingwindow_180.npz"
pca_15_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor15_rollingwindow_180.npz"

ipca_0_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_0_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_1_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_1_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_3_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_3_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_5_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_5_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_8_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_8_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_10_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_10_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_15_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_15_factors_210_initialMonths_180_window_0.001_cap.npz"

ipca_0_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_0_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_1_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_1_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_3_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_3_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_5_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_5_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_8_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_8_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_10_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_10_factors_210_initialMonths_180_window_0.001_cap.npz"
ipca_15_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_15_factors_210_initialMonths_180_window_0.001_cap.npz"

ff_0_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_0_factors_180_rollingWindow_0.001_Cap.npz"
ff_1_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_1_factors_180_rollingWindow_0.001_Cap.npz"
ff_2_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_2_factors_180_rollingWindow_0.001_Cap.npz"
ff_3_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_3_factors_180_rollingWindow_0.001_Cap.npz"
ff_4_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_4_factors_180_rollingWindow_0.001_Cap.npz"
ff_5_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_5_factors_180_rollingWindow_0.001_Cap.npz"
ff_6_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_6_factors_180_rollingWindow_0.001_Cap.npz"
ff_7_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_7_factors_180_rollingWindow_0.001_Cap.npz"

ff_0_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_0_factors_180_rollingWindow_0.001_Cap.npz"
ff_1_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_1_factors_180_rollingWindow_0.001_Cap.npz"
ff_2_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_2_factors_180_rollingWindow_0.001_Cap.npz"
ff_3_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_3_factors_180_rollingWindow_0.001_Cap.npz"
ff_4_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_4_factors_180_rollingWindow_0.001_Cap.npz"
ff_5_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_5_factors_180_rollingWindow_0.001_Cap.npz"
ff_6_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_6_factors_180_rollingWindow_0.001_Cap.npz"
ff_7_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_7_factors_180_rollingWindow_0.001_Cap.npz"
