
# Residual paths
pca_0_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor0_rollingwindow_60.npz"
pca_1_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor1_rollingwindow_60.npz"
pca_3_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor3_rollingwindow_60.npz"
pca_5_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor5_rollingwindow_60.npz"
pca_8_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor8_rollingwindow_60.npz"
pca_10_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor10_rollingwindow_60.npz"
pca_15_res_path: "factor_data/residuals/pca/OOSResiduals_PCA_factor15_rollingwindow_60.npz"

pca_0_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor0_rollingwindow_60.npz"
pca_1_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor1_rollingwindow_60.npz"
pca_3_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor3_rollingwindow_60.npz"
pca_5_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor5_rollingwindow_60.npz"
pca_8_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor8_rollingwindow_60.npz"
pca_10_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor10_rollingwindow_60.npz"
pca_15_residual_weights: "factor_data/residuals/pca/OOSResidualsmatrix_PCA_factor15_rollingwindow_60.npz"

ipca_0_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_0_factors_60_window.npz"
ipca_1_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_1_factors_60_window.npz"
ipca_3_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_3_factors_60_window.npz"
ipca_5_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_5_factors_60_window.npz"
ipca_8_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_8_factors_60_window.npz"
ipca_10_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_10_factors_60_window.npz"
ipca_15_res_path: "factor_data/residuals/ipca/IPCA_DailyMatrixOOSresiduals_15_factors_60_window.npz"

ipca_0_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_0_factors_60_window.npz"
ipca_1_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_1_factors_60_window.npz"
ipca_3_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_3_factors_60_window.npz"
ipca_5_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_5_factors_60_window.npz"
ipca_8_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_8_factors_60_window.npz"
ipca_10_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_10_factors_60_window.npz"
ipca_15_residual_weights: "factor_data/residuals/ipca/IPCA_DailyOOSresiduals_15_factors_60_window.npz"


ff_1_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_1_factors_60_rollingWindow.npz"
ff_3_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_3_factors_60_rollingWindow.npz"
ff_5_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_5_factors_60_rollingWindow.npz"
ff_8_res_path: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_8_factors_60_rollingWindow.npz"

ff_1_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_1_factors_60_rollingWindow.npz"
ff_3_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_3_factors_60_rollingWindow.npz"
ff_5_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_5_factors_60_rollingWindow.npz"
ff_8_residual_weights: "factor_data/residuals/fama_french/DailyFamaFrench_OOSresiduals_8_factors_60_rollingWindow.npz"
